[package]
name = "zmod4510-rs"
version = "1.0.0"
edition = "2021"

[dependencies]
esp-hal = {version = "0.20.1", features = [ "esp32c6", "async"] }
esp-hal-embassy     = { version = "0.3.0" }
log = { version = "0.4.20" }
